type IU = "Iue";
type Upper = Uppercase<IU>;
// type Upper = "IUE" 모든글자를 대문자로 변환
type Lower = Lowercase<IU>;
// type Lower = "iue" 모든글자를 소문자로 변환
type Capital = Capitalize<IU>;
// type Capital = "Iue" 첫글자만 대문자로 변환
type UnCaptial = Uncapitalize<IU>;
// type UnCaptial = "iue" 첫글자만 소문자로 변환